#!/usr/bin/env python3
## 쉬운 설명: HTML은 뼈대, CSS는 색과 배치, JavaScript는 버튼 동작이다.
"""b1-1 답안: 순수 HTML/CSS/JS 포트폴리오 생성기.
실행 후 생성 폴더에서 `python3 -m http.server 8080`을 실행한다.
다크 모드(localStorage), 햄버거, 부드러운 스크롤, IntersectionObserver,
폼 검증, GitHub API 로딩/성공/에러/빈 상태와 재시도를 포함한다."""
from pathlib import Path
import argparse

HTML = """<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>나의 포트폴리오</title><link rel="stylesheet" href="style.css"><script defer src="app.js"></script></head><body><header><nav><a href="#hero">NADO</a><button id="hamburger">☰</button><ul id="menu"><li><a href="#about">소개</a></li><li><a href="#skills">기술</a></li><li><a href="#projects">프로젝트</a></li><li><a href="#contact">문의</a></li><li><button id="theme">◐</button></li></ul></nav></header><main><section id="hero" class="reveal"><small>HELLO, WORLD</small><h1>문제를 코드로 푸는 개발자입니다.</h1><p>작은 아이디어를 사용자가 쓰는 경험으로 바꿉니다.</p><a class="button" href="#projects">프로젝트 보기</a></section><section id="about" class="reveal"><small>ABOUT</small><h2>저를 소개합니다</h2><p>웹의 기본 원리를 이해하고 접근성, 성능, 유지보수를 함께 고민합니다.</p></section><section id="skills" class="reveal"><small>SKILLS</small><h2>기술</h2><ul class="chips"><li>HTML</li><li>CSS</li><li>JavaScript</li><li>Python</li><li>Git</li><li>SQL</li></ul></section><section id="projects" class="reveal"><small>PROJECTS</small><h2>GitHub 프로젝트</h2><p id="state">로딩 중...</p><div id="projects-list" class="grid"></div><button id="retry" class="button hidden">다시 시도</button></section><section id="contact" class="reveal"><small>CONTACT</small><h2>문의</h2><form id="contact-form"><label for="name">이름</label><input id="name" required><span data-error="name"></span><label for="email">이메일</label><input id="email" type="email" required><span data-error="email"></span><label for="message">메시지</label><textarea id="message" required></textarea><span data-error="message"></span><button class="button">보내기</button><output id="result"></output></form></section></main><footer>© 2026 NADO · <a href="https://github.com">GitHub</a></footer></body></html>"""
CSS = """ :root{--bg:#f7f7f2;--surface:#fff;--text:#17202a;--muted:#68737d;--accent:#ee6c4d}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:16px system-ui;line-height:1.6}body.dark{--bg:#121820;--surface:#1d2935;--text:#edf2f7;--muted:#b8c4cf}header{position:sticky;top:0;background:color-mix(in srgb,var(--bg) 90%,transparent);backdrop-filter:blur(10px);z-index:2}nav{max-width:1000px;margin:auto;padding:1rem;display:flex;justify-content:space-between}nav a{color:var(--accent);font-weight:900;text-decoration:none}#menu{display:flex;gap:1rem;list-style:none;margin:0}#menu a{color:var(--text)}button{cursor:pointer}#hamburger{display:none}.reveal{max-width:1000px;margin:auto;padding:6rem 1rem;opacity:0;transform:translateY(25px);transition:.6s}.reveal.show{opacity:1;transform:none}h1{font-size:clamp(2.5rem,7vw,5rem);line-height:1.05}.button{display:inline-block;background:var(--accent);color:white;border:0;border-radius:999px;padding:.7rem 1.1rem;text-decoration:none}.chips{display:flex;gap:.7rem;flex-wrap:wrap;list-style:none;padding:0}.chips li,.card{background:var(--surface);padding:.7rem 1rem;border-radius:.7rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.card{box-shadow:0 8px 20px #0002}.hidden{display:none}form{display:grid;gap:.4rem;max-width:600px}input,textarea{font:inherit;padding:.7rem;background:var(--surface);color:var(--text);border:1px solid #aaa;border-radius:.4rem}textarea{min-height:130px}[data-error]{color:#c33;min-height:1.4em}footer{text-align:center;padding:3rem}@media(max-width:700px){#hamburger{display:block;background:none;border:0;font-size:1.4rem}#menu{display:none;position:absolute;top:4rem;left:0;right:0;background:var(--surface);padding:1rem;flex-direction:column}#menu.active{display:flex}}"""
JS = """const $=s=>document.querySelector(s);const menu=$("#menu");$("#hamburger").addEventListener("click",()=>menu.classList.toggle("active"));document.querySelectorAll("a[href^='#']").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();$(a.getAttribute("href")).scrollIntoView({behavior:"smooth"});menu.classList.remove("active")}));const saved=localStorage.getItem("theme");if(saved==="dark")document.body.classList.add("dark");$("#theme").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light")});const state=$("#state"),list=$("#projects-list"),retry=$("#retry");async function load(){state.textContent="로딩 중...";list.innerHTML="";retry.classList.add("hidden");try{const r=await fetch("https://api.github.com/users/KANGSIK-SEO/repos?per_page=6");if(!r.ok)throw Error();const repos=await r.json();if(!repos.length){state.textContent="표시할 프로젝트가 없습니다.";return}state.textContent="";list.innerHTML=repos.map(({name,description,html_url,stargazers_count,language})=>`<article class="card"><h3><a href="${html_url}" target="_blank">${name}</a></h3><p>${description||"설명 없음"}</p><small>★ ${stargazers_count} · ${language||"미상"}</small></article>`).join("")}catch(e){state.textContent="프로젝트를 불러올 수 없습니다.";retry.classList.remove("hidden")}}retry.addEventListener("click",load);load();document.querySelectorAll(".reveal").forEach(el=>new IntersectionObserver(([x],o)=>{if(x.isIntersecting){el.classList.add("show");o.disconnect()}},{threshold:.2}).observe(el));$("#contact-form").addEventListener("submit",e=>{e.preventDefault();let ok=true;["name","email","message"].forEach(id=>{const input=$("#"+id),error=$(`[data-error='${id}']`);error.textContent="";if(!input.value.trim()){error.textContent="필수 입력입니다.";ok=false}else if(id==="email"&&!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(input.value)){error.textContent="이메일 형식을 확인하세요.";ok=false}});if(ok){$("#result").textContent="문의가 접수되었습니다.";e.target.reset()}});"""


# main: 포트폴리오 파일을 생성하는 진입 함수.
def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path, default=Path("portfolio"))
    a = p.parse_args()
    for name, data in [("index.html", HTML), ("style.css", CSS), ("app.js", JS)]:
        f = a.out / name
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(data, encoding="utf-8")
    print("생성 완료:", a.out.resolve())


if __name__ == "__main__":
    main()
